---

- hosts: bastion  
  tasks:
  - name: Add two IPv4 DNS server addresses
    community.general.nmcli:
      conn_name: ens192
      type: ethernet
      dns4:
      - "{{ dns_server }}"
      state: present