- name: Check bastion anb node dns setting
  ansible.builtin.debug:
    msg: 
      - "{{ hostvars[item]['inventory_hostname_short'] }}.ocp.{{ domain_name }}.com IP: {{ hostvars[item]['ansible_host']}}, DNS record: {{ lookup('community.general.dig', hostvars[item]['inventory_hostname_short']+'.ocp.{{ domain_name }}.com' , '@{{ dns_server }}') }} "
  failed_when:
    - hostvars[item]['ansible_host'] not in lookup('community.general.dig', hostvars[item]['inventory_hostname']+'.ocp.'+hostvars[item]['domain_name']+'.com', '@'+hostvars[item]['dns_server'])
  with_items: 
    - "{{ groups['dns_bastion_group'] }}"
    - "{{ groups['bootstrap_group'] }}"
    - "{{ groups['dns_master_group'] }}"
    - "{{ groups['worker_group'] }}"