---

- name: Install httpd
  yum:
    name: httpd
    state: latest

- name: Change httpd.conf
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: Listen 80
    line: 'Listen 8080'

- name: Restart and Enable httpd
  service:
    name: httpd
    state: restarted
    enabled: yes

- name: Check httpd status
  command: systemctl status httpd
  register: result
  ignore_errors: true

- name: Show reoport
  debug:
    var: result