---

- name: Creates manifests
  command: openshift-install create manifests --dir=/root/ocp-data/

- name: Create ignition
  command: openshift-install create ignition-configs --dir=/root/ocp-data

- name: Copy ignition to http path
  copy:
    src: "/root/ocp-data/{{ item }}"
    dest: /var/www/html
    remote_src: yes
  loop:
    - bootstrap.ign
    - master.ign
    - worker.ign

- name: Give http path permission
  file:
    path: /var/www/html
    state: directory
    mode: '0755'
    recurse: yes